### ISSUE TITLE
Visuals for filter by assigned to self in WI list.

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ux#59] opened 2016-11-30 05:48 UTC
A button or toggle on work item list page to filter all the work items by assigned user as logged in user. If an user just want to see all the work items assigned to self he / she can toggle the filter on the list.

**Comment by mindreeper2420** [comment] 2016-11-30 13:02
@sanbornsen - there is already a UX issue for this. 

https://github.com/almighty/almighty-ux/issues/55

**Comment by mindreeper2420** [comment] 2016-11-30 15:47
Closing - duplicate of #55. Correct references updated in Core.

**Closed by mindreeper2420** 2016-11-30 15:47 UTC
